version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - amercier
  assignees:
  - amercier
  ignore:
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.2.8
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: next
    versions:
    - 10.1.0
